FROM python:3.11-slim

WORKDIR /app

COPY ui/requirements-ui.txt /app/requirements-ui.txt
RUN pip install --no-cache-dir -r /app/requirements-ui.txt

COPY ui/app.py /app/app.py

EXPOSE 8501
CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0", "--server.port=8501"]